languageCode = "en"
languageName = "English"
weight = 1
title = "NoVA PCB Design Hackathon"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  logo = "img/logo.png"
  description = "hackathon where people of all ages and skill levels get "
  copyright = "NoVA PCB Design Hackathon is fiscally sponsored by The Hack Foundation (d.b.a. Hack Club), a 501(c)(3) nonprofit (EIN: 81-2908499)"


[author]
name = "Micha Albert"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A high school student who loves PCBs! Organizer of NoVA PCB Design Hackathon"
links = [
  { github = "https://github.com/2231puppy" }
]
